<?php $this->headTitle('Unauthorized') ?>

<section class="col-md-8 col-md-offset-2 code_401">
  <h2>Unauthorized</h2>

  <p>
    You are not logged in, and therefore cannot perform this action.
  </p>

  <p>
    Login to continue:
  <p>

  <div class="btn-group-vertical" role="group">
    <a class="btn btn-default" href="<?= $this->auth_path ?>/github?redirect=<?= $this->redirect ?>">GitHub</a>
    <a class="btn btn-default" href="<?= $this->auth_path ?>/google?redirect=<?= $this->redirect ?>">Google</a>
    <?php if ($debug) : ?>
    <a class="btn btn-default" href="<?= $this->auth_path ?>/debug?redirect=<?= $this->redirect ?>">Debug</a>
    <?php endif ?>
  </div>
</section>
